-- CREATE TABLE users (
--     id SERIAL,
--     username VARCHAR(100) NOT NULL,
--     email VARCHAR(100) NOT NULL,
--     password VARCHAR(100) NOT NULL,
--     profile_id INTEGER FOREIGN KEY REFERENCES profiles(id)
-- );